// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_message.sql

package db

import (
	"context"
)

const createArticle = `-- name: CreateArticle :exec
INSERT INTO article (title, content, tags)
VALUES ($1, $2, $3)
`

type CreateArticleParams struct {
	Title   string
	Content string
	Tags    []string
}

func (q *Queries) CreateArticle(ctx context.Context, arg *CreateArticleParams) error {
	_, err := q.db.Exec(ctx, createArticle, arg.Title, arg.Content, arg.Tags)
	return err
}
