// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete-article-by-id.sql

package db

import (
	"context"
)

const deleteArticleByID = `-- name: DeleteArticleByID :exec
DELETE FROM article WHERE id = $1::integer
`

func (q *Queries) DeleteArticleByID(ctx context.Context, id uint64) error {
	_, err := q.db.Exec(ctx, deleteArticleByID, id)
	return err
}
