// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get-article-by-id.sql

package db

import (
	"context"
)

const getArticleByID = `-- name: GetArticleByID :one
SELECT
  id, title, content, tags, created_at, updated_at
FROM
  article
WHERE
  id = $1 :: integer
LIMIT
  1
`

func (q *Queries) GetArticleByID(ctx context.Context, id uint64) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
