// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get-articles-by-filter.sql

package db

import (
	"context"
	"time"
)

const getArticlesByFilter = `-- name: GetArticlesByFilter :many
SELECT
  id, title, content, tags, created_at, updated_at
FROM
  article
WHERE
  -- by title
  ($1::text IS NULL OR title LIKE $1::text)
  
  -- by tags
  AND (
    $2::text[] IS NULL 
    OR cardinality($2::text[]) = 0 
    OR tags && $2::text[]
  )
  
  -- by created_at
  AND ($3::timestamp IS NULL OR created_at >= $3::timestamp)
  AND ($4::timestamp IS NULL OR created_at <= $4::timestamp)
  
  -- by updated_at
  AND ($5::timestamp IS NULL OR updated_at >= $5::timestamp)
  AND ($6::timestamp IS NULL OR updated_at <= $6::timestamp)
ORDER BY
  -- by title
  CASE WHEN $7::text = 'title' AND $8::text = 'asc' THEN title END ASC,
  CASE WHEN $7::text = 'title' AND $8::text = 'desc' THEN title END DESC,
  
  -- by created_at
  CASE WHEN $7::text = 'created_at' AND $8::text = 'asc' THEN created_at END ASC,
  CASE WHEN $7::text = 'created_at' AND $8::text = 'desc' THEN created_at END DESC,
  
  -- by updated_at
  CASE WHEN $7::text = 'updated_at' AND $8::text = 'asc' THEN updated_at END ASC,
  CASE WHEN $7::text = 'updated_at' AND $8::text = 'desc' THEN updated_at END DESC,
  
  -- default
  created_at DESC
LIMIT
  $10::integer OFFSET $9::integer
`

type GetArticlesByFilterParams struct {
	FilterSearchTitle string
	FilterSearchTags  []string
	FilterCreatedFrom time.Time
	FilterCreatedTo   time.Time
	FilterUpdatedFrom time.Time
	FilterUpdatedTo   time.Time
	OrderByField      string
	OrderType         string
	OffsetPage        uint64
	LimitPage         uint64
}

func (q *Queries) GetArticlesByFilter(ctx context.Context, arg *GetArticlesByFilterParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, getArticlesByFilter,
		arg.FilterSearchTitle,
		arg.FilterSearchTags,
		arg.FilterCreatedFrom,
		arg.FilterCreatedTo,
		arg.FilterUpdatedFrom,
		arg.FilterUpdatedTo,
		arg.OrderByField,
		arg.OrderType,
		arg.OffsetPage,
		arg.LimitPage,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
