// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get-articles-by-filter.sql

package db

import (
	"context"
	"time"
)

const getArticlesByFilter = `-- name: GetArticlesByFilter :many
SELECT
  id, title, content, tags, created_at, updated_at
FROM
  article
WHERE
  CASE
    -- by title
    WHEN $1 :: text IS NULL THEN TRUE
    ELSE title LIKE $1
  END
  AND CASE
    -- by tags
    WHEN $2 :: text [] IS NULL
    OR cardinality($2) IS NULL
    OR cardinality($2) = 0 THEN TRUE
    ELSE tags & & $2
  END
  AND CASE
    -- by filter_created_from
    WHEN $3 :: timestamp IS NULL THEN TRUE
    ELSE created_at >= $3
  END
  AND CASE
    -- by filter_created_to
    WHEN $4 :: timestamp IS NULL THEN TRUE
    ELSE created_at <= $4
  END
  AND CASE
    -- by filter_updated_from
    WHEN $5 :: timestamp IS NULL THEN TRUE
    ELSE updated_at >= $5
  END
  AND CASE
    -- by filter_updated_to
    WHEN $6 :: timestamp IS NULL THEN TRUE
    ELSE updated_at <= $6
  END
`

type GetArticlesByFilterParams struct {
	FilterSearchTitle string
	FilterSearchTags  []string
	FilterCreatedFrom time.Time
	FilterCreatedTo   time.Time
	FilterUpdatedFrom time.Time
	FilterUpdatedTo   time.Time
}

func (q *Queries) GetArticlesByFilter(ctx context.Context, arg *GetArticlesByFilterParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, getArticlesByFilter,
		arg.FilterSearchTitle,
		arg.FilterSearchTags,
		arg.FilterCreatedFrom,
		arg.FilterCreatedTo,
		arg.FilterUpdatedFrom,
		arg.FilterUpdatedTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
