// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Article struct {
	ID        uint64
	Title     string
	Content   string
	Tags      []string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}
