// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update-article.sql

package db

import (
	"context"
)

const updateArticle = `-- name: UpdateArticle :exec
UPDATE
  article
SET
  title = COALESCE($1, title),
  content = COALESCE($2, content),
  tags = COALESCE($3 :: text [], tags)
WHERE
  id = $4 :: integer
`

type UpdateArticleParams struct {
	NewTitle   *string
	NewContent *string
	NewTags    []string
	ID         uint64
}

func (q *Queries) UpdateArticle(ctx context.Context, arg *UpdateArticleParams) error {
	_, err := q.db.Exec(ctx, updateArticle,
		arg.NewTitle,
		arg.NewContent,
		arg.NewTags,
		arg.ID,
	)
	return err
}
